#
# CSE183 Assignment 9 Backend
#

openapi: '3.0.3'

info:
  description: CSE183 Assignment 9 Backend
  version: 0.1.0
  title: CSE183 Assignment 9 Backend

servers:
  - url: http://localhost:3010/v0

paths:
  /mail:
      get:
        parameters:
          - in: query
            name: mailbox
            schema:
              type: string
          - in: query
            name: from
            schema:
              type: string
        description: Returns all Email
        responses:
          200:
            description: Email Response
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/EmailResponse'
          404:
            description: Mailbox doesnt exist
          default:
            description: Unexpected Error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
  /mail/{id}:
    put:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: query
          name: unread
          schema:
            type: string
          required: false
        - in: query
          name: mailbox
          schema:
            type: string
          required: false
        - in: query
          name: starred
          schema:
            type: string
          required: false
      description: Returns Email by ID
      responses:
        204:
          description: Email Response
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    EmailResponse:
      type: array
      properties:
        Inboxes: 
          type: array
          items:
            $ref: '#/components/schemas/InboxType'

    InboxType:
      type: array
      properties:
        name:
          type: string
        mail:
          type: array
          items:
            $ref: '#/components/schemas/Email'
      required:
        - name
        - mail

    Email:
      type: object
      properties:
        id:
          type: string
        mailbox:
          type: string
        mail:
          type: object
          properties:
            to:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
              required:
                - name
                - email
            subject:
              type: string
            sent:
              type: string
            received:
              type: string
            content:
              type: string
            from:
              type: object
              properties:
                from-name:
                  type: string
                from-email:
                  type: string
          required:
            - subject
            - content
      
    To:
      type: object
      properties:
        to-name:
          type: string
        to-email:
          type: string
        

    From:
      type: object
      properties:
        from-name:
          type: string
        from-email:
          type: string